# Generated by Django 5.0.6 on 2024-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_capteur', models.CharField(max_length=50)),
                ('nom_capteur', models.CharField(max_length=50)),
                ('periode_temps', models.DateTimeField()),
                ('valeur', models.FloatField()),
            ],
        ),
    ]
